---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: pre-run | update apt-cache
    tags: always
    apt: update_cache=yes
    changed_when: False
    when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:
  - name: install htop
    package:
      name: htop

